---
- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
