---
- name: reload sysctl
  command: sysctl -p /etc/sysctl.d/99-sre-lab.conf

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted

- name: restart docker
  systemd:
    name: docker
    state: restarted
