server {
    listen 80;
    server_name zhourui2000.online www.zhourui2000.online;

    root /usr/share/nginx/html;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /usr/share/nginx/html;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;
}
